# -*- coding: utf-8 -*-
"""Extração_de_texto_artigos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqO4VZ9833q3VPO1o7QdCMlUAMv3a6da

# Técnicas de Pré-processamento para OCR

# Importando as bibliotecas
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

"""Para ler aquivos pdfs"""

!apt-get install poppler-utils

!pip install pdf2image

"""#INSIRA AQUI O DOCUMENTO PDF"""

from pdf2image import convert_from_path
#Upe o arquivo e copie seu caminho aqui
pages = convert_from_path('/content/MiniSat.pdf.crdownload')

for i in range(len(pages)):

    pages[i].save('page'+ str(i) +'.jpg', 'JPEG')

"""#CASO UPE ARQUIVOS DO DRIVE"""

#caso vá upar imagem do drive, use isso
from google.colab import drive
drive.mount('/content/drive')

"""# Detecção de textos"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract

"""#ARQUIVOS EM PORTUGUÊS"""

#Compile isso caso use artigos em português
!mkdir tessdata
!wget -O ./tessdata/por.traineddata https://github.com/tesseract-ocr/tessdata/blob/main/por.traineddata?raw=true

"""#ARTIGOS EM INGLÊS"""

#Compile caso vá usar artigos em inglês
!mkdir tessdata
!wget -O ./tessdata/eng.traineddata https://github.com/tesseract-ocr/tessdata/blob/main/eng.traineddata?raw=true

"""# bote a imagem aqui

"""

img = cv2.imread('/content/page0.jpg')
cv2_imshow(img)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

val, thresh = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)
cv2_imshow(thresh)
print(val)

invert = 255 - thresh
cv2_imshow(invert)

config_tesseract = '--tessdata-dir tessdata'
texto=pytesseract.image_to_string(thresh, lang='eng', config=config_tesseract)

output_file_path = 'output_text.txt'
with open(output_file_path, 'w') as file:
    file.write(texto)

print(f'Resultado salvo no arquivo "{output_file_path}"')

#lendo o arquivo.txt em inglês
arquivo = open("output_text.txt", "r")
conteudo = arquivo.read()
print(conteudo)
arquivo.close()

!pip install deep-translator

from deep_translator import GoogleTranslator

from deep_translator import GoogleTranslator

tradutor = GoogleTranslator(source="english", target="portuguese")
arquivo = open("output_text.txt", "r")
conteudo = arquivo.read()
print(conteudo)
arquivo.close()

# Dividindo o texto em pedaços de menos de 5.000 caracteres
caracteres_size = 4500
text_caracteres = [conteudo[i:i+caracteres_size] for i in range(0, len(conteudo), caracteres_size)]

# Traduza cada pedaço e combine os resultados
traducao = ""
for fatias in text_caracteres:
    traducao += tradutor.translate(fatias)

print(traducao)

